<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rekapan_stok_model extends CI_Model
{

    public $table = 'rekapan_stok';
    public $id = 'id_rekapan_stok';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_rekapan_stok', $q);
        $this->db->or_like('id_menu', $q);
        $this->db->or_like('tanggal_penjualan', $q);
        $this->db->or_like('stok_terjual', $q);
        $this->db->or_like('stok_sisa', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
    function laporan_stok_total($q = NULL, $dari, $sampai)
    {
        // $this->db->like('id_rekapan_stok', $q);
        // $this->db->or_like('id_menu', $q);
        // $this->db->or_like('tanggal_penjualan', $q);
        // $this->db->or_like('stok_terjual', $q);
        // $this->db->or_like('stok_sisa', $q);
        $this->db->where('tanggal_penjualan >=', $dari);
        $this->db->where('tanggal_penjualan <=', $sampai);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_rekapan_stok', $q);
        $this->db->or_like('id_menu', $q);
        $this->db->or_like('tanggal_penjualan', $q);
        $this->db->or_like('stok_terjual', $q);
        $this->db->or_like('stok_sisa', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function laporan_stok($limit, $start = 0, $q = NULL, $dari, $sampai)
    {
        $this->db->order_by($this->id, $this->order);
        // $this->db->like('id_rekapan_stok', $q);
        // $this->db->or_like('id_menu', $q);
        // $this->db->or_like('tanggal_penjualan', $q);
        // $this->db->or_like('stok_terjual', $q);
        // $this->db->or_like('stok_sisa', $q);
        $this->db->where('tanggal_penjualan >=', $dari);
        $this->db->where('tanggal_penjualan <=', $sampai);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file Rekapan_stok_model.php */
/* Location: ./application/models/Rekapan_stok_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-08 16:02:56 */
/* http://harviacode.com */