<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Stok_menu_model extends CI_Model
{

    public $table = 'stok_menu';
    public $id = 'id_stok_menu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id_custom
    function get_by_id_custom($id)
    {
        $this->db->where('id_menu', $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_stok_menu', $q);
        $this->db->or_like('id_menu', $q);
        $this->db->or_like('jumlah_stok_menu', $q);
        $this->db->or_like('terjual', $q);
        $this->db->or_like('sisa', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('mfb.nama_menu,sm.id_stok_menu,sm.id_menu, sm.jumlah_stok_menu,sm.terjual,sm.sisa');
        $this->db->from('stok_menu sm');
        $this->db->join('menu_food_and_beverage mfb', 'sm.id_menu = mfb.id_menu', 'left');
        $this->db->like('sm.id_stok_menu', $q);
        $this->db->or_like('mfb.nama_menu', $q);
        // $this->db->or_like('sm.id_menu', $q);
        $this->db->or_like('sm.jumlah_stok_menu', $q);
        $this->db->or_like('sm.terjual', $q);
        $this->db->or_like('sm.sisa', $q);
        $this->db->group_by('sm.id_menu');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file Stok_menu_model.php */
/* Location: ./application/models/Stok_menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-27 07:09:05 */
/* http://harviacode.com */